# Generated by Django 5.0.4 on 2024-05-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nannies", "0003_nanny_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nanny",
            name="gender",
            field=models.CharField(
                choices=[("M", "男"), ("F", "女"), ("O", "其它")], max_length=1
            ),
        ),
    ]
