# Generated by Django 5.0.4 on 2024-05-17 19:49

import positions.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
